dataset_path: 'tqabench_8k_path'
task: "tqabench_8k"
test_split: test
output_type: generate_until

doc_to_text:   !function utils.tqabench_doc_to_text
doc_to_target: !function utils.tqabench_doc_to_target
process_results: !function utils.tqabench_process_results

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."

generation_kwargs:
  max_new_tokens: 16
  temperature: 0.2
  do_sample: true

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.MultiChoiceRegexFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "([A-Z])\\."

metric_list:
  - metric: tqabench_score_overall
    aggregation: !function utils.tqabench_aggregation
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
